[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'privgov'
type = 'CosmosSdk'
rpc_addr = 'http://0.0.0.0:26657'
event_source = { mode = "push", url = "ws://0.0.0.0:26657/websocket", batch_delay = "1000ms" }
grpc_addr = 'http://0.0.0.0:9090'
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'cosmos'
key_name = 'ak'
store_prefix = 'ibc'
default_gas = 1000000
max_gas = 4000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '10s'
max_block_time = '30s'
trusting_period = '14days'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 1
denom = 'stake'

[chains.address_type]
derivation = 'cosmos'


[[chains]]
id = 'fairyring_devnet'
type = 'CosmosSdk'
rpc_addr = 'http://0.0.0.0:36657'
event_source = { mode = "push", url = "ws://0.0.0.0:36657/websocket", batch_delay = "1000ms" }
grpc_addr = 'http://0.0.0.0:9190'
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'fairy'
key_name = 'fk'
store_prefix = 'ibc'
default_gas = 1000000
max_gas = 4000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '10s'
max_block_time = '30s'
trusting_period = '14days'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 1
denom = 'stake'

[chains.address_type]
derivation = 'cosmos'
